### ISSUE TITLE
Bug with classes derived from dict

### ISSUE THREAD

**Issue by parnell** [jeff-hykin/json_fix#3]
Hi Jeff, 
I've used this plugin before and never had any issues, but most recently I had a problem like the following where a class uses dict as a parent class in which case __json__ is not called. 

Versions:
json-fix: 0.5.2
python: 3.11

Example code to demonstrate the problem.
```python
import json
import json_fix

class Test(dict):
    def __json__(self):
        raise Exception("__json__ was called")

print("Case #1 fails", end=": ")
with open("test.json", "w") as f:
    try:
        json.dump(Test(), f)
        print("I should have failed but __json__ was not called")
    except:
        print("__json__ worked as expected!")

print("Case #2 works", end=": ")
try:
    json.dumps(Test())
    print("I should have failed but __json__ was not called")
except:
    print("__json__ worked as expected!")
```
Output from the above: 
```
Case #1 fails: I should have failed but __json__ was not called
Case #2 works: __json__ worked as expected!
```

Anyway to resolve this?

**Comment by jeff-hykin** [comment]
I haven't had a chance to test this myself yet, but if that is the current issue then its a major problem! Thank you for reporting. I'll look into this the next chance I get

**Comment by jeff-hykin** [comment]
Bad news: turns out python bypasses all of the normal encoder calls specifically for `json.dump` of builtin objects. 
So to fix this bug, we'll need to patch `json.dump` which could be more risky to patch than the encoder.

**Comment by jeff-hykin** [comment]
I published v1.0.0 just now that seems to fix that behavior while maintaining the old-good behavior. However, there is one caveat.

If someone does `from json import dumps` before `import json_fix` is called, then I believe they will get the old behavior. I don't know that anything can be done in that situation though.

**Comment by parnell** [comment]
Thanks Jeff! I'll check it out to see if it fixes my use case.

**Comment by parnell** [comment]
Fix seem good for me! Thanks Jeff. 

As for the problem case, I always use `import json` and call `load/s` and `dump/s` from there so the issue won't hit for me at least. 

Also wanted to note anyone that uses an auto import organizer would have that issue as the `import json_fix` will naturally get placed after any native library imports. So maybe a warning somewhere about that particular issue.
